### ISSUE TITLE
Set default pin states for relays

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/automation-hat#15]
See: https://forums.pimoroni.com/t/automation-hat-node-red-nodes/6640/2

**Comment by ronnyvdbr** [comment]
I was able to resolve the problem.
The problem lies within your init library, where you initialise the gpio pins for the relays.
There seems to be a missing parameter on line 188:

GPIO.setup(self.pin, GPIO.OUT, initial=0)

the initial=0 parameter was missing which determines the startup state of the pins which controls the relays.

https://github.com/pimoroni/automation-hat/blob/master/library/automationhat/init.py

**Comment by Gadgetoid** [comment]
Was fixed in 90b45b56e641e9fb19e6c1381380e71ce99ad04c
